make deemphasis text accessible, add arg types to EzTextStyle and EzLabel
ezcater/recipe pull request #1053
Opened 2023-09-18 20:56 UTC by danidewitt

## What did we change?
- Make deemphasis text accessible, this affects `EzTextStyle`, `EzLabel`, and `EzTable` column headers
- Add arg types to `EzLabel` and `EzTextStyle` (`EzTable` was already done)

## Why are we doing this?
- Accessibility

## Screenshot(s) / Gif(s):
<img width="968" alt="Screenshot 2023-09-18 at 4 51 20 PM" src="https://github.com/ezcater/recipe/assets/3790037/c0abb303-d016-450d-adc1-a3732a3efbdf">
<img width="717" alt="Screenshot 2023-09-18 at 4 51 46 PM" src="https://github.com/ezcater/recipe/assets/3790037/19b99259-1f39-47c1-adbd-91820379e6ae">
<img width="721" alt="Screenshot 2023-09-18 at 4 52 16 PM" src="https://github.com/ezcater/recipe/assets/3790037/47bd74c1-5a9d-4b92-85fc-f08496ed47dd">

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes
 
[Contributing guidelines](https://recipe.ezcater.com/?path=/docs/guides-contributing--docs)

2023-09-18 21:14 UTC, pgrippi submitted a review, later dismissed

2023-09-19 12:49 UTC, noranda requested changes
Just a few minor change requests (apply them to both components). Otherwise, looks good!

2023-09-19 12:49 UTC, noranda commented on packages/recipe/src/components/EzLabel/Documentation/Stories/Default.stories.tsx
> +  render: (args: Props) => (
I've been renaming these where needed to make the exports more explicit.

```suggestion
  render: (args: EzLabelProps) => (
```

2023-09-19 12:49 UTC, noranda commented on packages/recipe/src/components/EzLabel/Documentation/Stories/Default.stories.tsx
> +      type: {name: 'string', required: false},
This line can be removed (same with the other props). I still need to go back and clean up some of the other components, but it's only needed if the prop is required.
```suggestion
```

2023-09-19 12:49 UTC, noranda commented on packages/recipe/src/components/EzLabel/Documentation/Stories/Default.stories.tsx
> +    use: {
I've been putting these props in alphabetical order, just to make it easier to find props for components with a ton of them. The table will sort them, but it helps maintenance.

2023-09-19 12:49 UTC, noranda commented on packages/recipe/src/components/EzLabel/Documentation/Stories/Default.stories.tsx
> +      description: 'The style of the label for the selected size.',
```suggestion
      description: 'The use or variant of the label.',
```
To be consistent with descriptions of other components with this prop.

2023-09-19 12:49 UTC, noranda commented on packages/recipe/src/components/EzTextStyle/Documentation/Stories/Default.stories.tsx
> +      description: 'The emphasis style of the text element.',
```suggestion
      description: 'The use or variant of the text element.',
```

2023-09-19 12:49 UTC, noranda commented on packages/recipe/src/components/EzTextStyle/Documentation/Stories/Default.stories.tsx
> +  },
```suggestion
    playroom: {code: <EzTextStyle>This is some example text.</EzTextStyle>},
```
No `dedent` needed here. It's only needed if there is more than one line.

2023-09-19 13:00 UTC, noranda commented
We also might want to take a closer look at `EzField` dropdowns with groups after this change. The new color makes the group labels almost indistinguishable from the options. @alexanderlippner16?


<img width="487" alt="Screenshot 2023-09-19 at 8 58 58 AM" src="https://github.com/ezcater/recipe/assets/5418735/6a093df2-8968-4116-83ff-a9e68f519d5a">

2023-09-25 20:07 UTC, danidewitt commented
@noranda i added a horizontal line between the grouping label and its items per @alexanderlippner16 request
<img width="543" alt="Screenshot 2023-09-25 at 3 41 46 PM" src="https://github.com/ezcater/recipe/assets/3790037/1b8e09e5-1fd7-4334-9d29-041a95ba4642">

2023-09-25 20:30 UTC, pgrippi approved these changes

2023-09-25 20:30 UTC, pgrippi commented on packages/recipe/src/components/EzField/EzListBox.tsx
> +    color: '#F0F2F7', // this is a new color from color tokens, we're adding this divider for accessibility purposes before moving to new color tokens
minor but can this `color` rule be moved up next to all of the other ones? I don't think we need to nest it under `&`

2023-09-25 20:38 UTC, danidewitt commented on packages/recipe/src/components/EzField/EzListBox.tsx
> +    color: '#F0F2F7', // this is a new color from color tokens, we're adding this divider for accessibility purposes before moving to new color tokens
it's under `&` for specificity to avoid using !important

2023-09-26 12:47 UTC, noranda approved these changes

2023-09-26 14:21 UTC, merged