fix: add accessible title to truncated EzCard headings
ezcater/recipe pull request #1066
Opened 2023-10-12 14:49 UTC by danidewitt

## What did we change?
- Added accessible title to truncated heading for EzCard

## Why are we doing this?
- Accessibility

## Screenshot(s) / Gif(s):
<img width="1295" alt="Screenshot 2023-10-12 at 10 32 18 AM" src="https://github.com/ezcater/recipe/assets/3790037/a4af011b-8bf2-45c6-9459-b941007d7190">

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes
 
[Contributing guidelines](https://recipe.ezcater.com/?path=/docs/guides-contributing--docs)

2023-10-13 17:38 UTC, noranda requested changes
Can the titles be split here? So hovering over the title will just show the title, and hovering over the subtitle will just show the subtitle. It seems odd to combine them like this for both.

2023-10-13 17:38 UTC, noranda commented on packages/recipe/src/components/EzCard/EzCardHeading.tsx
> +      <EzHeading size="3" subheading={subtitle} title={truncateHeading ? accessibileTitle : null}>
A minor note, but best practice is to use `undefined` here which means "do not use this attribute". See [definitions](https://exploringjs.com/impatient-js/ch_undefined-null.html#undefined-vs.-null).

```suggestion
      <EzHeading size="3" subheading={subtitle} title={truncateHeading ? accessibileTitle : undefined}>
```

2023-10-17 13:17 UTC, noranda approved these changes
🚀

2023-10-17 14:48 UTC, jmargolisvt approved these changes

2023-10-17 14:54 UTC, pgrippi approved these changes

2023-10-17 15:21 UTC, merged