feat: Add EzStackedBarChart component
ezcater/recipe pull request #1076
Opened 2023-10-25 19:57 UTC by danidewitt

⚠️ This is a WIP draft. Do NOT review yet. I'm just putting up a draft PR while I'm OOO in case it needs to be picked up before Monday, 10/30.

Small things to clean up before it's ready for review:

- [ ] Handle TODO comments (required)
- [ ] Custom tooltip should follow cursor (required)
- [ ] Box shadow on the tooltip (design says this can wait until v2 if needed)
- [ ] Legend label font size (required)
- [ ] Update displayData arg type (required)
- [ ] Check for parity of features/styling with `EzBarChart` where it makes sense (required)
- [ ] Provide a default color scale (optional)
- [ ] Any other default props? (optional)
- [ ] Write docs, including stories (required)
- [ ] Legend squares should have a selection state when the corresponding bar is hovered (design says this can wait until v2 if needed)
- [ ] Grey highlight behind hovered stacked bar (design says this can wait until v2 if needed)
- [ ] Write tests (required, including a test that tests for 2+ sets of data, make sure axes labels still work)
- [ ] Snapshot (optional)
- [ ] Update with main (required, should be very little conflict since it's a new component)

## What did we change?
- Add `EzStackedBarChart` component

## Why are we doing this?
- Design request

## Screenshot(s) / Gif(s):
WIP screenshots:
<img width="761" alt="Screenshot 2023-10-25 at 10 20 07 AM" src="https://github.com/ezcater/recipe/assets/3790037/a64b6bb5-4f1c-4006-940a-d4d7defef0ff">
<img width="758" alt="Screenshot 2023-10-25 at 10 20 50 AM" src="https://github.com/ezcater/recipe/assets/3790037/94628343-73ff-4b12-a28d-86145ff8d3cb">

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes
 
[Contributing guidelines](https://recipe.ezcater.com/?path=/docs/guides-contributing--docs)

2023-11-02 14:47 UTC, noranda requested changes
Nice job! I have a few requested changes and a clarification question below.

1. Clicking on the preview button in the Component Library breaks the app.
2. The playroom examples don't work.
3. See various other change requests in the code.

I realize that having more than one data set requires a separate implementation, but this component's arg types are nearly identical to `EzBarChart`. Is there a way we could combine them into a single component and render the correct implementation depending on number of data sets provided? I know this would mean a breaking change, but perhaps it is the correct thing to do here? (CC @alexanderlippner16)

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.mdx
> +import {Canvas, Controls, Meta, Primary, Source, Story, Unstyled} from '@storybook/blocks';
```suggestion
import {Canvas, Controls, Meta, Primary, Source, Story} from '@storybook/blocks';
```

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.mdx
> +import EzAlert from '../../EzAlert';
```suggestion

```

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.mdx
> +- Bar charts are good for comparing relative size.
Can we add some verbiage here to make clear that this component is only to be used when there is more than one data set? And link to `EzBarChart` if not?

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Documentation/Stories/Default.stories.tsx
> +    <Box sx={{width: '50%'}}>
Could we make this a little wider? The tooltips are a little tough to read at this width.

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.mdx
> +    export type DisplayData = {
```suggestion
    type DisplayData = {
```

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.snapshot.tsx
As this is only a preview, I would recommend not rendering the component here and instead rendering something that looks like the component (see `EzBarChart`), otherwise you can run into rendering issues when it's clicked on.

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Documentation/Stories/Default.stories.tsx
> +    displayData: {
We call this `data` in `EzBarChart`. Should these match?

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Implementations/CustomTooltip.tsx
> +        >
Should we use MUI components for this? We should also use design tokens where possible.

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Implementations/CustomTooltip.tsx
> +              const color = useThemeColor(barColor);
Is there another way we can write this where we don't have to break this hooks rule?

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Implementations/EzStackedBarChartVictory.tsx
> +          fill: useThemeColor(datum.barColor),
Can we pull this out so we don't have to break this hooks rule?

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Implementations/EzStackedBarChartVictory.tsx
> +              const barFillColor = useThemeColor(datum.barColor);
Can we break this out?

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/__tests__/EzStackedBarChart.test.tsx
> +describe('EzBarChart', () => {
```suggestion
describe('EzStackedBarChart', () => {
```

2023-11-02 14:47 UTC, noranda commented on packages/recipe/src/components/index.ts
> +export {default as EzStackedBarChart} from './EzStackedBarChart';
Can we sort this?

2023-11-06 20:41 UTC, danidewitt commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.mdx
> +- Bar charts are good for comparing relative size.
it says "over multiple categories" and each dataset is a category in a bar chart

2023-11-06 20:41 UTC, danidewitt commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.mdx
> +    export type DisplayData = {
i'm actually using this, which is why it is exported

2023-11-06 20:42 UTC, danidewitt commented on packages/recipe/src/components/EzStackedBarChart/Documentation/Stories/Default.stories.tsx
> +    displayData: {
this is more than just data, it also includes color and label information for each set of data, so i'd argue it should be different

2023-11-06 21:10 UTC, danidewitt commented on packages/recipe/src/components/EzStackedBarChart/Implementations/CustomTooltip.tsx
> +        >
this was in my list for v2 due to deadlines, but i just did it

2023-11-06 21:11 UTC, danidewitt commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.snapshot.tsx
is that true for our other components too? because i see a bunch of other components rendering the component

2023-11-06 21:24 UTC, danidewitt commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.snapshot.tsx
the rendering issue was just a case i hadn't accounted for, i think this is otherwise fine now.

2023-11-06 21:41 UTC, danidewitt commented
@noranda i've responded to all the comments and implemented relevant changes.

as for why it's a separate component, actually bar charts and stacked bar charts are not the same (as [noted](https://github.com/ezcater/recipe/pull/1076/files#diff-109006220a7809c181328d175acac0d23ade47a1002a43b417305cf55f4a2caeR16) in the documentation), even though they have similar (but different) props. see the difference explained [here](https://www.storytellingwithdata.com/blog/stacked-bars). specifcially: 
>  While this may seem obvious, a stacked bar chart is not the same as a [standard bar chart](https://www.storytellingwithdata.com/blog/2020/2/19/what-is-a-bar-chart). A traditional bar chart displays a single categorical variable in the form of bars. A stacked bar chart shows two categorical variables. The first (and primary) variable is shown along the entire length of the bar, and the second variable is represented as stacks within each categorical bar.

we're in the process of breaking apart our other components, like EzField, and i think we've seen the complexity and problems that arise when you smash multiple components into one, try to make the props "figure" things out, then need to pull the components apart.

2023-11-07 13:48 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.mdx
> +- Bar charts are good for comparing relative size.
It says "especially" which makes it seem like it's fine to use this component with a single category. Is that the case?

2023-11-07 14:03 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.mdx
> +    export type DisplayData = {
This is just the MDX though, no? In an case, not a big deal.

2023-11-07 14:04 UTC, noranda commented on packages/recipe/src/components/EzStackedBarChart/Documentation/EzStackedBarChart.snapshot.tsx
If the component is highly interactive (like a chart) I would suggest we abstract the component so that we don't run into rendering issues, but so long as it works here, I'm fine with it.

2023-11-07 14:27 UTC, noranda requested changes
The changes look good, except for one clarification and the playroom examples still don't work.

With regard to keeping this a separate component, I'd still like @alexanderlippner16 to weigh in, but otherwise I'm fine with it. While it's true that some components should be broken out (like `EzField`), this is because we need to mix and match inputs in groups. I don't think we need to do anything like that here, but I'll let Alexis make that call.

2023-11-07 14:37 UTC, danidewitt commented
@noranda what's wrong with the playroom examples? they're working for me:
<img width="998" alt="Screenshot 2023-11-07 at 9 36 02 AM" src="https://github.com/ezcater/recipe/assets/3790037/5cd2800f-5b1d-41f3-8da7-95f24bcd9dec">

2023-11-07 15:20 UTC, noranda approved these changes

2023-11-07 15:23 UTC, danidewitt commented
@noranda as for the separate component: we did discuss making it a separate component in meetings and everyone was 👍 with it. it's the highest priority request, if it's not what we want, we need to let our customer know it's going to be a longer wait.

in any case, i still stand by stacked bar charts being a separate kind of chart than bar charts, given the argument in the article i [linked above](https://www.storytellingwithdata.com/blog/stacked-bars). the props need to be different, the tooltip is different, the purpose is different. there are many variations on stacked bar charts that we might want in the future, and i can see bar charts becoming impossibly bloated and difficult to maintain if we don't separate them now. two examples that immediately come to mind: cluster bar charts and cluster stacked bar charts.

2023-11-07 15:24 UTC, pgrippi approved these changes

2023-11-07 15:28 UTC, merged