Dd icon rating
ezcater/recipe pull request #763
Opened 2022-02-15 18:10 UTC by danidewitt

## What did we change?

## Why are we doing this?

## Screenshot(s) / Gif(s):

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`npm run changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2022-02-15 19:26 UTC, ez-alexfrazer commented on src/components/EzRating/Implementations/EzRatingCustom/EzRatingCustom.tsx
> +    <span role="img" aria-label={label}>
🎱 would this be more accessible as a [meter](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter) element? It also allows for some more granular control of [styling](https://css-tricks.com/html5-meter-element/)

2022-02-15 20:58 UTC, morgannegagne commented on src/components/EzRating/EzRating.md
> +## Examples
Is it worth having an example with a `label` prop?

2022-02-15 21:00 UTC, morgannegagne approved these changes

2022-02-16 16:30 UTC, ez-alexfrazer commented on src/components/EzRating/Implementations/EzRatingCustom/EzRatingCustom.tsx
> +    <span role="img" aria-label={label}>
I think the accessibility on this might be unclear, would a [`meter`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter) component make sense in this case?

> The <meter> [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents either a scalar value within a known range or a fractional value.

2022-02-16 16:30 UTC, danidewitt commented on src/components/EzRating/EzRating.types.ts
> +  fullIcon: EzIconTypes;
I'm still thinking about this default icon bit, maybe we can just import the three free default icons and it be ok... I'll add it and we can test the performance of it.

2022-02-16 16:35 UTC, spdonegan1 approved these changes

2022-02-16 18:47 UTC, danidewitt commented on src/components/EzRating/Implementations/EzRatingCustom/EzRatingCustom.tsx
> +    <span role="img" aria-label={label}>
we're doing what [mui does for rating](https://mui.com/components/rating/#accessibility) - they use a `span` with `role="img"` and `aria-label=`${label}``

2022-02-16 20:22 UTC, noranda requested changes
This looks great!

I like the idea of having a default icon (star?). Maybe we can use a free-license icon for this so we don't run into issues. We also might want to think about future uses of this, for example, we might want to only round to the nearest whole icon, or we might want to make these interactive at some point. For now though, I think this works for the required use case.

_Requested changes:_
I would suggest adding some logic tests to make sure we are rounding the values correctly. The Playroom is also not working correctly as it cannot import the icons.

2022-02-17 15:10 UTC, maggiedbaker approved these changes
looks good! I also like the idea of defaulting to a star icon, but either way is fine. Just curious, do we have any use cases currently that wouldn't be a star?

2022-02-24 15:39 UTC, danidewitt commented on src/components/EzRating/EzRating.types.ts
> +  fullIcon: EzIconTypes;
@noranda and @maggiedbaker i think this thread answers your questions

2022-02-24 21:20 UTC, danidewitt commented
@noranda and @maggiedbaker  most of your questions are answered in the [thread](https://github.com/ezcater/recipe/pull/763#discussion_r814007308) above.

- adding default icon: this is definitely a performance issue, but also potentially a licensing issue.
- cases that aren't a star: yes, we have price ratings implemented several different ways in other projects, and i can imagine having heart rating or other icon ratings
- rounding to a whole number: if you want to round to something less precise than 0.5, i think this is fine to happen when you use the icon, so `Math.floor(value)` for your `value` prop (or `Math.ceil()`, you can decide if you want to be less precise)
- making it interactive: we can always add another interactive implementation of ratings later (maybe it's even a separate component that uses this read-only component)

@noranda i added tests and fixed the playroom

2022-02-24 21:30 UTC, danidewitt commented
visual tests passing
<img width="262" alt="Screen Shot 2022-02-24 at 4 29 48 PM" src="https://user-images.githubusercontent.com/3790037/155610921-b28cf0ba-75b1-4585-987e-8ceec088d02a.png">

2022-02-24 22:19 UTC, noranda requested changes
The logic tests and playroom look great!

One last suggestion:

We should probably have boundaries for the values that extend outside the `0 - max` range. Currently a value of 100 will render 100 stars. We could restrict the values just in case (if value > max, value = max & if value < 0, value = 0).

2022-02-25 16:08 UTC, danidewitt commented
@noranda good catch - i added a check for value > max and value < 0 and tests for both of those cases.

2022-02-25 16:16 UTC, danidewitt commented
visual tests passing 
<img width="262" alt="Screen Shot 2022-02-25 at 11 16 34 AM" src="https://user-images.githubusercontent.com/3790037/155749490-2d5354b0-fda6-444f-8d13-84a7ea69562c.png">

2022-02-25 16:21 UTC, noranda approved these changes
Good to go!

2022-02-25 23:19 UTC, danidewitt commented
tests passing
<img width="366" alt="Screen Shot 2022-02-25 at 6 17 52 PM" src="https://user-images.githubusercontent.com/3790037/155815817-b7d50452-fb33-415f-9dd3-110233764b7c.png">

2022-02-25 23:20 UTC, merged