first pass mui progress
ezcater/recipe pull request #764
Opened 2022-02-25 16:27 UTC by danidewitt

## What did we change?

## Why are we doing this?

## Screenshot(s) / Gif(s):

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`npm run changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2022-02-25 21:27 UTC, maggiedbaker commented on src/components/EzProgress/EzProgress.md
> +## Best Pracitices
should be `Practices` :)

2022-02-25 21:40 UTC, maggiedbaker commented on src/components/EzProgress/EzProgress.tsx
> +  const calculateProgressColor = () => {
🎱 🎱 Maybe rename this to something like `calculateProgressColorFromGoals`, to differentiate it from the `let progressColor`, etc., logic below, which is also determining the progress color?

2022-02-25 21:42 UTC, pgrippi commented on src/components/EzProgress/EzProgress.tsx
> +const EzProgress = forwardRef<Ref, EzProgressProps>(({value, goal, subgoal, color, label}, ref) => {
🎱 what do you think about `subGoal`? react usually camel cases props

2022-02-25 21:42 UTC, pgrippi commented on src/components/EzProgress/EzProgress.tsx
> +  else progressValue = value;
this could be extracted to a util:

```ts
const clamp = (x: number): number => Math.max(0, Math.min(100, x));
```

2022-02-25 21:45 UTC, maggiedbaker commented on src/components/EzProgress/EzProgress.md
> +Provide _either_ `goal` with `subgoal` _or_ `color`. Don't provide `color` _and_ `goal` with `subgoal`. Don't provide `color` _and_ `goal` with `subgoal`.
This line is repeated twice here `Don't provide `color` _and_ `goal` with `subgoal`

2022-02-25 21:47 UTC, maggiedbaker commented on src/components/EzProgress/EzProgress.md
> +
Repeated line: Don't provide `color` _and_ `goal` with `subgoal`

2022-02-25 21:52 UTC, danidewitt commented on src/components/EzProgress/EzProgress.md
> +## Best Pracitices
thanks for always catching my docs typos!

2022-02-25 21:53 UTC, danidewitt commented on src/components/EzProgress/EzProgress.tsx
> +  const calculateProgressColor = () => {
i like it 👍

2022-02-25 21:54 UTC, danidewitt commented on src/components/EzProgress/EzProgress.tsx
> +const EzProgress = forwardRef<Ref, EzProgressProps>(({value, goal, subgoal, color, label}, ref) => {
i didn't camelcase it because it's a [word](https://www.merriam-webster.com/dictionary/subgoal)

2022-02-25 21:54 UTC, danidewitt commented on src/components/EzProgress/EzProgress.tsx
> +const EzProgress = forwardRef<Ref, EzProgressProps>(({value, goal, subgoal, color, label}, ref) => {
but i'm open to it if its easier... it wasn't easy to find a word for this prop

2022-02-25 21:55 UTC, danidewitt commented on src/components/EzProgress/EzProgress.md
> +Provide _either_ `goal` with `subgoal` _or_ `color`. Don't provide `color` _and_ `goal` with `subgoal`. Don't provide `color` _and_ `goal` with `subgoal`.
👍 🥇

2022-02-25 21:56 UTC, danidewitt commented on src/components/EzProgress/EzProgress.md
> +
repeated...twice

2022-02-25 21:56 UTC, pgrippi commented on src/components/EzProgress/EzProgress.tsx
> +      <EzProgressMui value={progressValue} color={progressColor} boldDisplayValue={(goal && subgoal && !meetsSubGoal) ? true : false} hasNumericValue={hasNumericValue} />
you can remove the ternary for `boldDisplayValue`:

```jsx
boldDisplayValue={goal && subgoal && !meetsSubGoal}
```

2022-02-25 21:56 UTC, pgrippi commented on src/components/EzProgress/EzProgress.tsx
> +  else progressColor = PROGRESS_COLORS[color];
🎱 what would you think about using a nested if instead of splitting the logic between here and a function?

```
let progressColor;
if(!hasNumericValue) progressColor = PROGRESS_COLORS.gray; 
else if(goal && subgoal) {
  if (meetsGoal) progressColor = PROGRESS_COLORS.green;
  else if (!meetsGoal && meetsSubGoal) progressColor = PROGRESS_COLORS.yellow;
  else progressColor = PROGRESS_COLORS.red;
}
else progressColor = PROGRESS_COLORS[color];
```

2022-02-25 21:56 UTC, noranda requested changes
Wow, this looks awesome with MUI!

Just a few suggested changes on top of what you already mentioned.

2022-02-25 21:56 UTC, noranda commented on src/components/EzProgress/EzProgress.md
> +Provide _either_ `goal` with `subgoal` _or_ `color`. Don't provide `color` _and_ `goal` with `subgoal`. Don't provide `color` _and_ `goal` with `subgoal`.
Typo: duplicated sentence.

2022-02-25 21:56 UTC, noranda commented on src/components/EzProgress/EzProgress.md
> +Provide _either_ `goal` with `subgoal` _or_ `color`. Don't provide `color` _and_ `goal` with `subgoal`. Don't provide `color` _and_ `goal` with `subgoal`.
Typo: duplicated sentence.

2022-02-25 21:56 UTC, noranda commented on src/components/EzProgress/EzProgress.md
> +## Best Pracitices
Typo: Best Practices

2022-02-25 21:56 UTC, noranda commented on src/components/EzProgress/Implementations/EzProgressMui/EzProgressMui.tsx
> +    >
Since this is a flex component, instead of `Box` I would suggest using `Stack` here, which is a flex component by default.

Also, for styling components like `Box` and `Stack`, you can use any [system properties](https://mui.com/system/properties/) as direct attributes instead of using in the `sx` prop. Technically either works, but I think splitting them up is more efficient and looks nicer.

```js
<Stack alignItems="center" justifyContent="center" p="20% 0">
```

2022-02-25 21:56 UTC, noranda commented on src/components/EzProgress/Implementations/EzProgressMui/EzProgressMui.tsx
> +      </Box>
I would also switch this out with a `Stack` component.

```js
<Stack fontSize="30px" fontWeight={`${boldDisplayValue ? '500' : '300'}`}>
```

2022-02-25 21:56 UTC, danidewitt commented on src/components/EzProgress/EzProgress.tsx
> +  else progressValue = value;
mui calls it clamp too...

2022-02-25 21:56 UTC, pgrippi commented on src/components/EzProgress/EzProgress.tsx
> +const EzProgress = forwardRef<Ref, EzProgressProps>(({value, goal, subgoal, color, label}, ref) => {
mind blown! I'm fine with leaving it as is 👍🏻

2022-02-25 21:57 UTC, noranda commented on src/components/EzProgress/EzProgress.md
> +Provide _either_ `goal` with `subgoal` _or_ `color`. Don't provide `color` _and_ `goal` with `subgoal`. Don't provide `color` _and_ `goal` with `subgoal`.
Oops just realized we all caught the same typos, lol. Sorry for the coordinated comment attacks!

2022-02-25 21:58 UTC, danidewitt commented on src/components/EzProgress/EzProgress.tsx
> +  else progressValue = value;
do you find it easier to read that way though?

2022-02-25 21:58 UTC, noranda commented on src/components/EzProgress/EzProgress.tsx
> +const EzProgress = forwardRef<Ref, EzProgressProps>(({value, goal, subgoal, color, label}, ref) => {
`subgoal` is totally a word!

2022-02-25 21:59 UTC, noranda commented on src/components/EzProgress/EzProgress.tsx
> +  else progressValue = value;
+1 for this idea!

2022-02-25 22:00 UTC, danidewitt commented on src/components/EzProgress/EzProgress.tsx
> +  else progressColor = PROGRESS_COLORS[color];
that's how i had it originally... and i didn't like the nested if, but i could be convinced

2022-02-25 22:02 UTC, danidewitt commented on src/components/EzProgress/Implementations/EzProgressMui/EzProgressMui.tsx
> +    >
i did this because that's how they do it in [this example](https://mui.com/components/progress/#CircularWithValueLabel.js) on the mui docs

2022-02-25 22:02 UTC, danidewitt commented on src/components/EzProgress/Implementations/EzProgressMui/EzProgressMui.tsx
> +      </Box>
same as above, [mui example](https://mui.com/components/progress/#CircularWithValueLabel.js)

2022-02-25 22:02 UTC, pgrippi commented on src/components/EzProgress/EzProgress.tsx
> +  else progressColor = PROGRESS_COLORS[color];
yeah it's not a strong opinion, I only thought of it because it keeps all of the color settings together in one block

2022-02-25 22:04 UTC, pgrippi commented on src/components/EzProgress/EzProgress.tsx
> +  else progressValue = value;
> do you find it easier to read that way though?

only in that it shrinks the component size down and you can inline it with the rest of the attributes:

```jsx
<EzProgressMui value={clamp(progressValue)} />
```

but I also didn't account for `value` being undefined, which `clamp` will return as `NaN`

2022-02-25 22:07 UTC, danidewitt commented on src/components/EzProgress/EzProgress.tsx
> +  else progressValue = value;
i still i like the idea of it - i'm going to leave it for now because `NaN`. i think we should extract a clamp util for this component and the rating component to use after i get everything merged though!

2022-02-25 22:08 UTC, pgrippi commented
this looks great! ✅

2022-02-25 22:09 UTC, danidewitt commented on src/components/EzProgress/Implementations/EzProgressMui/EzProgressMui.tsx
> +    >
ok i'm changing it to stack!

2022-02-25 22:12 UTC, noranda commented on src/components/EzProgress/Implementations/EzProgressMui/EzProgressMui.tsx
> +    >
Yeah I notice the MUI docs use `sx` for these components sometimes and other times they don't. ¯\_(ツ)_/¯

2022-02-25 22:32 UTC, pgrippi approved these changes
you might consider running `npx prettier -w src` to have prettier cleanup the extra whitespace

this looks great!

2022-02-25 22:38 UTC, danidewitt commented
visual regression tests passing
<img width="269" alt="Screen Shot 2022-02-25 at 5 38 00 PM" src="https://user-images.githubusercontent.com/3790037/155812541-c8facbf8-7b36-4d14-8d49-50f9b00138a9.png">

2022-02-25 23:38 UTC, danidewitt commented
visual tests passing

<img width="350" alt="Screen Shot 2022-02-25 at 6 38 20 PM" src="https://user-images.githubusercontent.com/3790037/155817342-7582f20b-19e0-426c-a5ec-8c98960c73e8.png">

2022-02-26 00:12 UTC, danidewitt commented
tests passing

<img width="347" alt="Screen Shot 2022-02-25 at 7 11 39 PM" src="https://user-images.githubusercontent.com/3790037/155819626-f26a5dd2-dbe0-4e98-9292-376e9b53061d.png">

2022-02-26 00:14 UTC, danidewitt commented
@noranda @maggiedbaker the only thing left for this one and cutting the major release is your ✅ on this one!

2022-02-28 15:14 UTC, noranda approved these changes
Looks good! I see a few spacing/quotes prettier issues, so I would recommend running prettier first, but all tests pass and everything work splendidly. Nice work!

2022-02-28 17:06 UTC, maggiedbaker approved these changes
Looks good and is working well in the canary release!

<img width="997" alt="Screen Shot 2022-02-28 at 9 43 49 AM" src="https://user-images.githubusercontent.com/4922450/156026465-c3af8f67-626a-4d71-a065-f9fd138893b5.png">

2022-02-28 17:23 UTC, danidewitt commented
tests still passing
<img width="268" alt="Screen Shot 2022-02-28 at 12 22 36 PM" src="https://user-images.githubusercontent.com/3790037/156029064-be95fdfc-4ea4-45b7-b88e-2745f725617f.png">

2022-02-28 17:23 UTC, merged