feat: add mui themes, convert EzProgress to use new theme
ezcater/recipe pull request #792
Opened 2022-03-23 19:42 UTC by noranda

*Note: this work is branched off `nb/bump-emotion` and should be merged after https://github.com/ezcater/recipe/pull/780.*

## What did we change?

This PR does the following:
- Adds the following Material UI emotion themes to Recipe:
  - `ezTheme`
  - `ezMarketplaceTheme` - extends `ezTheme`
  - `ezFulfillmentTheme` - extends `ezTheme`
- Adds new `EzThemeProvider` component that will eventually replace `EzProvider` currently used for stitches theming. All new components using the new themes will need to be wrapped in this provider. ***[BREAKING CHANGE]***
- Wraps the doc site `Layout` component in the new `EzThemeProvider` to use the new themes.
- Updates the *Getting Started* doc site page, removing an outdated styling section, removing support for IE11, and adding a new *Recipe themes* section that summarizes the changes in Recipe v14, including:
  - Supported themes - a list of the supported emotion themes
  - Theme provider - describes how to use the new `EzThemeProvider` component which provides access to the new themes
  - Extending themes - describes how to extend these new themes
  - Importing theme properties - describes how to access the new theme properties such as color variables
- Adds a new *Migration Guide* for Recipe v14 including describing breaking changes and gives examples for how to use the new themes.
- Wraps all tests and playrooms in the new `EzThemeProvider`.
- Moves playroom themes into its own file using the default `ezTheme`. Prior to this, we were using the `standard` theme which was a legacy theme. This does not change the playroom for existing components and allows us to add additional themes to the playroom in the future as we see fit.
- Updates the `EzProgress` and related components to use the new `ezTheme` instead of stitches.
  - Also updated image snapshots due to standardizing to `neutral120` color (from `#f4f7f8` to `#f5f7f7`)

## Why are we doing this?

This PR is the second in a series of PRs that will make up the Recipe v14 release as follows:
1. Bump emotion to v11.
2. ***[THIS PR]*** Add MUI themes and update EzProgress (the only new MUI component currently using themes) to use the new theme.
3. Add all stitches themes into new MUI themes to be exportable.
4. Remove any unused legacy themes.

## Checklist

- [x] Create a changeset (`npm run changeset`) with a summary of the changes

2022-03-28 17:19 UTC, danidewitt requested changes
couple questions (in addition to the inline comments):
1. why'd the `EzProgress` tests generate new snapshots?
2. it looks like the inverted `EzProgress` goals aren't rendering correctly (border color) on the doc-site, but the tests didn't fail (?) 
<img width="516" alt="Screen Shot 2022-03-28 at 12 30 10 PM" src="https://user-images.githubusercontent.com/3790037/160452553-7943e4d5-c681-4aaf-8925-6177bc217eb7.png">

2022-03-28 17:19 UTC, danidewitt commented on doc-site/src/pages/migrating-to-recipe-14.md
> +With the maturity of emotion and the decision to integrate Material UI into Recipe to help make it a more robust library, new and existing components will begin to be built using Material UI and emot
With the decisions to deprecate IE11 and Recipe in Rails support and to integrate third-party component implementations (like Material UI), new and existing components are being converted to emotion. During this process, current stitches-styled components will be supported until all components have been converted, at which point all stitches-related themes and styles will be deprecated.

2022-03-28 17:19 UTC, danidewitt commented on doc-site/src/pages/migrating-to-recipe-14.md
> +If you are using emotion themes in your app, you will now be able to extend these themes to create a customized theme. You will also be able to import these themes and theme properties for use in oth
same comment as before about if we want to encourage custom themes philosophically

2022-03-28 17:19 UTC, danidewitt commented on doc-site/src/pages/migrating-to-recipe-14.md
> +3. In order for Recipe components to access the new themes, they will need to be wrapped in the `EzThemeProvider` component and passed the appropriate theme. This is usually done at the app level, bu
same comment as before about nesting

2022-03-28 17:21 UTC, danidewitt commented on doc-site/src/pages/migrating-to-recipe-14.md
> +## Importing theme properties
same as previous comment about source of truth

2022-03-28 17:35 UTC, noranda commented
Thanks for the review, @danidewitt!

> 1. why'd the EzProgress tests generate new snapshots?

We switched to the standardized `neutral120` color (from `#f4f7f8` to `#f5f7f7`). A very slight difference, but enough to require generating new snapshots.

> 2. it looks like the inverted EzProgress goals aren't rendering correctly (border color) on the doc-site, but the tests didn't fail (?)

Hmm. I'm not sure why it's not rendering correctly for you. It seems to render fine in my local setup. I will look into this.

![image](https://user-images.githubusercontent.com/5418735/160454556-924fa1e3-2fd0-4345-a5d7-7014e73ac167.png)

2022-03-28 17:54 UTC, noranda commented on doc-site/src/pages/guides/getting-started.md
> -- [Why Recipe](#why-recipe)
The links are redundant as they act as a TOC, when we already have a TOC to the right. We do this a little inconsistently across the doc site (ex. Principles doesn't do it, but Contributing does).

2022-03-28 18:05 UTC, noranda commented on doc-site/src/pages/guides/getting-started.md
> +To use, wrap your Recipe components in the `EzThemeProvider` component and pass in the appropriate theme. This is usually done at the app level, but can be nested if needed.
Nesting theme providers allows users to contextually adjust styles if needed. It's how you can do things like make brand-specific extended themes that only get applied to a specific set of pages or components that the theme provider wraps. It's not as common, but I don't think we should not recommend doing so.

2022-03-28 18:05 UTC, noranda commented on doc-site/src/pages/guides/getting-started.md
> +### Extending themes
I think we need to allow extending themes while maintaining the standard themes in Recipe. There are cases where the themes will need to be extended (ex. menu branding). However, we could add some additional text here that states this should only be done when there is a valid use case for it.

2022-03-28 18:08 UTC, noranda commented on src/components/EzProgress/__tests__/EzProgress.test.tsx
> +const scope = {EzProgress, EzPage, EzCard, EzThemeProvider, ezTheme};
Yes, we will need to add these to the scope for all MUI-themed components. When we refactor the doc site, we could l create a global scope to use.

2022-03-28 18:23 UTC, noranda commented on src/components/EzThemeProvider/EzThemeProvider.md
> +---
This is a good question. I included it because we have one for `EzProvider`, but I don't see it displayed anywhere. It's not a typical component, so we probably want to discuss where, if anywhere, it should live.

2022-03-28 18:27 UTC, noranda commented on doc-site/src/pages/migrating-to-recipe-14.md
> +With the maturity of emotion and the decision to integrate Material UI into Recipe to help make it a more robust library, new and existing components will begin to be built using Material UI and emot
Good point!

2022-03-30 17:59 UTC, danidewitt approved these changes
Great work on this! 🎉 

Let's do a canary release downstream test with @maggiedbaker and @pgrippi before we 🚢 .

2022-03-30 18:22 UTC, danidewitt approved these changes

2022-03-30 18:27 UTC, pgrippi approved these changes

2022-03-30 18:28 UTC, merged