style: update EzButton secondary styling for marketplace theme
ezcater/recipe pull request #817
Opened 2022-04-20 21:34 UTC by danidewitt

## What did we change?
- Updated styling for EzButton secondary variant marketplace theme

## Why are we doing this?
- Request from @ktlnux 
<img width="1180" alt="Screen Shot 2022-04-20 at 5 33 02 PM" src="https://user-images.githubusercontent.com/3790037/164326633-039afe7e-7161-409f-bc6b-12217f5081e2.png">

## Screenshot(s) / Gif(s):
Before:
<img width="647" alt="Screen Shot 2022-04-20 at 5 33 26 PM" src="https://user-images.githubusercontent.com/3790037/164326673-1a6af4e7-b084-4d34-a85d-216a4f13605a.png">

After:
<img width="522" alt="Screen Shot 2022-04-20 at 5 33 15 PM" src="https://user-images.githubusercontent.com/3790037/164326696-606d6cc8-e62b-4064-a386-fb5f97345111.png">

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2022-04-20 22:10 UTC, pgrippi approved these changes

2022-04-25 21:15 UTC, pgrippi commented on packages/recipe/src/components/theme.config.ts
> +      wide: '3px',
you will need a recipe changelog for this so that you get a recipe release, otherwise if store upgrades just the theme it won't have the `$wide` variable

2022-04-25 21:17 UTC, danidewitt commented
updated to match all the new secondary button states: default, hover, active, focus

<img width="721" alt="Screen Shot 2022-04-25 at 5 15 12 PM" src="https://user-images.githubusercontent.com/3790037/165176590-36de4b2f-5ece-4ba2-969b-f14b2fc499e7.png">

2022-04-25 21:19 UTC, danidewitt commented on packages/recipe/src/components/EzButton/EzButton.theme.config.ts
> +      'button-secondary-focus': '$wide',
@pgrippi this whole file also needs a recipe release

2022-04-26 14:22 UTC, noranda commented
@danidewitt This looks good, except now when clicking on the button, the focus border is shifting it over slightly. Also happens with the fulfillment theme.

2022-04-27 20:33 UTC, danidewitt commented
@pgrippi @noranda this could use thorough 👀 since so many things are named similarly and i've been staring at it for a while

2022-04-29 17:32 UTC, noranda requested changes

2022-04-29 17:32 UTC, noranda commented on packages/recipe-ui-theme-marketplace/src/index.ts
>    },
This difference in border-width is still causing a shift in the button for `focus`+`hover`. Instead, you could use `box-shadow` to create the border, like we do with the primary button.

```suggestion
  borderWidths: {
    'card-border': '$thin',
    'button-secondary': '$thin',
  },
```

2022-04-29 17:32 UTC, noranda commented on packages/recipe-ui-theme-marketplace/src/index.ts
> +    'button-secondary-focus-ring': '0 0 3px rgba(63, 97, 255, 0.3)',
Changing this `box-shadow` for secondary buttons would give the appearance of a border so we don't have to deal with changing border widths which cause shifting of the element.

```suggestion
    'button-secondary-focus-ring': '0 0 0 3px rgba(180, 190, 237, 1)',
```
<img width="88" alt="Screen Shot 2022-04-29 at 1 28 54 PM" src="https://user-images.githubusercontent.com/5418735/165993939-d3717f10-4310-4b86-b86b-18b3e0e05efe.png">

2022-05-18 14:41 UTC, danidewitt commented on packages/recipe-ui-theme-marketplace/src/index.ts
>    },
done!

2022-05-18 14:41 UTC, danidewitt commented on packages/recipe-ui-theme-marketplace/src/index.ts
> +    'button-secondary-focus-ring': '0 0 3px rgba(63, 97, 255, 0.3)',
done!

2022-05-18 14:43 UTC, pgrippi approved these changes

2022-05-18 14:49 UTC, noranda approved these changes
Looks good!

2022-05-18 19:39 UTC, noranda approved these changes

2022-05-18 19:40 UTC, pgrippi approved these changes

2022-05-18 19:40 UTC, merged