Dd/marketplace carousel
ezcater/recipe pull request #831
Opened 2022-05-18 20:48 UTC by danidewitt

## What did we change?
- Updated the carousel according to the new functionality and design (see below)
- Updated docs, cookbook, snippets, tests, styles, etc.

## Why are we doing this?
- New design/functionality from design team

<img width="767" alt="Screen Shot 2022-05-18 at 4 45 23 PM" src="https://user-images.githubusercontent.com/3790037/169152728-fbdf03ef-bd72-40cd-8d5c-78de3d0da106.png">

<img width="530" alt="Screen Shot 2022-05-18 at 4 45 55 PM" src="https://user-images.githubusercontent.com/3790037/169152770-79f1ec76-cf4a-4c01-a231-12ff3e1d8b7e.png">

## Screenshot(s) / Gif(s):
<img width="1447" alt="Screen Shot 2022-05-18 at 4 46 31 PM" src="https://user-images.githubusercontent.com/3790037/169152976-b0f2bddb-2ad5-49b0-ab84-511317667674.png">
<img width="841" alt="Screen Shot 2022-05-18 at 4 46 43 PM" src="https://user-images.githubusercontent.com/3790037/169152981-eca01d5f-f2c5-4bf5-b7c2-e841037a91d0.png">
<img width="450" alt="Screen Shot 2022-05-18 at 4 46 50 PM" src="https://user-images.githubusercontent.com/3790037/169152983-4574ee11-b22f-4031-a561-715824181dc0.png">

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2022-05-18 22:17 UTC, pgrippi commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +  });
this is recreating the listeners every time this component renders, but `updateResponsiveStates` is recomputed every time `items` is changed, which happens every time the parent component renders. you could get around this by either making `updateResponsiveStates` stable (by converting `items` to a ref), or sticking `updateResponsiveStates` in its own ref (which feels a little redundant given that `useCallback` is supposed to return a stable function as often as possible)

you can see what I mean by adding a console log here:

```jsx
  useEffect(() => {
    console.log('setting updateResponsiveStates');
    window.addEventListener('resize', updateResponsiveStates);
    return () => {
      window.removeEventListener('resize', updateResponsiveStates);
    };
  }, [updateResponsiveStates]);
```

and adding this to the playroom for the carousel example:

```jsx
  const [foo, setFoo] = React.useState(1);

  return (
    <EzPage>
      <div><button type="button" onClick={() => setFoo(f => f + 1)}>click me</button></div>
      <EzCarousel title="Practical example" description="practical example description">
```

every time you click the button you'll see the events are detached and recreated, even though you have `updateResponsiveStates` as a dependency:

<img width="696" alt="Screen Shot 2022-05-18 at 6 16 26 PM" src="https://user-images.githubusercontent.com/1180841/169164762-7b78c692-fa7f-4ee4-b187-4b5611990879.png">

2022-05-18 22:30 UTC, pgrippi commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +          id="carousel-items"
this will case a DOM error if there are multiple carousels on the page (meaning multiple sections with the same `id`), you could suffix it with the id you generate above:

```jsx
id={`carousel-items-${id}`}
```

2022-05-19 16:53 UTC, danidewitt commented
⚠️ DO NOT MERGE. ⚠️ 

this will be part of the v15 release, so it needs to change the base branch. when i get back, i'll have to rebase, update migration docs, etc., in addition to PR feedback.

2022-05-19 17:38 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +          id="carousel-items"
well i had every intention of making this a real unique id! good catch

2022-05-19 17:56 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +const EzCarouselCustom = ({items, title, link, description, onPageChange, ref}) => {
sorry, for clarification - converting `items` to `React.Children.toArray(children)` will create an additional problem we don't have a solution for?

2022-05-19 18:10 UTC, pgrippi commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +const EzCarouselCustom = ({items, title, link, description, onPageChange, ref}) => {
yes, sadly!

Every time the parent component re-renders, you'll get new `children` (in react they are component functions, so even if the children didn't change the functions are new functions, so they are not seen as identical)

however, every time this `EzCarouselCustom` component renders its `items` don't change. This is why using `[items]` as a hook dependency ends up working for rerenders of just this compnoent, and you don't end up in an infinite loop

As soon as you do `React.Children.toArray(items)`, you will get a new array of children every time you render, causing hooks to see it as a change and recalculate, causing the component to render, and then you'll get a brand new `items` array, causing the hooks to recalculate, causing this component to render, ad infinitum

So doing the bad thing of using `children` as an array without `Children.toArray` is actually what makes this all work!

2022-05-19 18:16 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +  }, [scrollPosition]);
when i make this change, i see the onPageChange events fire twice, which makes it look visually i've never changed pages on the carousel (this example: http://localhost:8000/cookbook/responsive-carousel/): 

```
page changed!, previous:  0 current:  1
page changed!, previous:  1 current:  0
```

perhaps related to my other issues though

2022-05-19 18:16 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +  }, [scrollPosition]);
even though i just said that, i recoginze your points were valid about stability

2022-05-19 19:45 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +  }, [scrollPosition]);
oh it's because when you click the buttons, it changes the page twice

```
  useEffect(() => {
    if (page !== scrollPosition) {
      handlePageChange(page, scrollPosition);
    }
  }, [page, scrollPosition, handlePageChange]);
```

because it's getting called from `handlePageChangeNext` or `handlePageChangePrevious` and then again above even though there was no scrolling, just clicking

2022-05-20 15:22 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +  }, [scrollPosition]);
we took care of this in https://github.com/ezcater/recipe/pull/832

2022-05-20 15:22 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +  });
we took care of this in https://github.com/ezcater/recipe/pull/832

2022-05-20 15:22 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +const EzCarouselCustom = ({items, title, link, description, onPageChange, ref}) => {
we took care of this in https://github.com/ezcater/recipe/pull/832

2022-05-20 15:24 UTC, danidewitt commented
@noranda we tested some feedback in https://github.com/ezcater/recipe/pull/832 so i need to get that PR approved and merged into this one first

2022-05-20 17:31 UTC, noranda requested changes
This is a great start, nice job!

I think there are a few things we need to address before this is ready for release. I added some comments in the code and will put the rest of them in separate comments below so it's easier to comment on each one.

2022-05-20 17:33 UTC, noranda reviewed
.

2022-05-20 17:36 UTC, noranda commented
The carousel preview image on the Components page should be updated to look like the new design.
  Current:
  <img width="290" alt="Screen Shot 2022-05-20 at 10 08 20 AM" src="https://user-images.githubusercontent.com/5418735/169579745-1ff9220f-e347-4745-b222-c59a51fa36b5.png">

2022-05-20 18:45 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/EzCarousel.md
> -- Be used to preview items and indicate that more items may be available, other than what is currently shown.
we don't show a preview on desktop anymore - the functionality is different

2022-05-20 18:48 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/utils.tsx
> +};
this is 100% based on the figma specifications - the responsive size names are just reasonable variable names based on the figma specifications

2022-05-20 18:50 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/utils.tsx
> +    if you change the sizes, then the card/images heights get weird */
i don't think we should be adjusting the child sizes becuase they could hand us cards or other kinds of children. 

and depending on if the child is a card, the height between the cards differ depending on if it's a card with an image in it.

2022-05-20 18:52 UTC, danidewitt commented
@noranda i think the bugs you mentioned are fixed in the other branch, which is why that one needed to be merged into this branch before reviewing this PR

2022-05-20 18:52 UTC, danidewitt commented
note to self: need to address this comment in this PR https://github.com/ezcater/recipe/pull/832#pullrequestreview-980528419

2022-05-20 18:59 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/EzCarousel.md
> +The carousel will automatically determine how many slides to show per page, as well as whether to show navigational buttons or use horizontal scroll.
i didn't see this because i've been connected to my monitor - but i do see it on my laptop.

2022-05-20 19:00 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/EzCarousel.md
> +    onPageChange={({previous, current}) => console.log('previous:', previous, 'current:', current)}
i know what the issue is with this example

2022-05-20 19:01 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/EzCarousel.md
>    const caterers = [
that's an existing example, so i just added numbers to each card title like the responsive example

2022-05-20 19:02 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +        <Box sx={carouselHeaderStyles(carouselItemListContainer, responsiveValues, responsiveSize)}>
this is residual from trying to make other things work properly

2022-05-20 19:02 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +          <Box component="div" sx={carouselHeaderButtonGroupStyles}>
this is also residual from trying to make other things work properly

2022-05-20 19:05 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +                key={item && item.key ? item.key : index}
this was changed in the other PR to different logic

2022-05-20 19:05 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselStyles.tsx
> +      responsiveValues[responsiveSize].maxContainerWidth,
this was also changed in the other PR

2022-05-20 19:14 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/EzCarousel.md
> +The carousel will automatically determine how many slides to show per page, as well as whether to show navigational buttons or use horizontal scroll.
same comment about card widths - it is really weird to be changing the widths of the cards because they could pass us anything, plus the height of the cards gets weird if we try to shrink them, especially if there is an image in it

2022-05-20 19:16 UTC, noranda commented on packages/recipe/src/components/EzCarousel/EzCarousel.md
> +The carousel will automatically determine how many slides to show per page, as well as whether to show navigational buttons or use horizontal scroll.
Yeah that's a good question, I'm not sure exactly how it should behave. Maybe a question for @ktlnux?

2022-05-20 19:16 UTC, noranda commented on packages/recipe/src/components/EzCarousel/EzCarousel.md
> +The carousel will automatically determine how many slides to show per page, as well as whether to show navigational buttons or use horizontal scroll.
Yeah that's a good question, I'm not sure exactly how it should behave. Maybe a question for @ktlnux?

2022-05-20 19:19 UTC, noranda commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/utils.tsx
> +    if you change the sizes, then the card/images heights get weird */
Perhaps another question for @ktlnux?

2022-05-20 19:25 UTC, noranda commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/utils.tsx
> +};
Sorry, I think I might have made things confusing. I think the logic in this function is fine (except maybe the names `smallMobile` and `largeMobile`. My question is about how we're implementing the behavior. We're basically saying if the _container_ width is < 768px, treat it as if it's mobile and allow horizontal scrolling. I think it should be if the _device_ width is < (whatever size we determine is mobile), then we treat it as mobile and allow horizontal scrolling. As it is now, only the container needs to be < 768px and we give it horizontal scrolling, which I don't think we should do per the design spec. Our doc site is the perfect example of this. Containers can be small and we shouldn't use horizontal scrolling on desktops of any size (assuming a standardized _device_ width cutoff).

2022-05-20 19:25 UTC, danidewitt commented
to do list: 
- [ ] preview image update
- [ ] carousel flickers when changing pages with buttons (this was fixed in https://github.com/ezcater/recipe/pull/832)
- [ ] buttons shifting when paging right then left (this was fixed in https://github.com/ezcater/recipe/pull/832)
- [ ] remove scrollTo browser support section 
- [ ] marketplace image border radius to 5px
- [ ] are we changing this implementation for both themes? yes because fulfillment doesn't use it @noranda 
- [ ] cards can extend outside the container
- [ ] scrolling to end takes you back to the beginning https://github.com/ezcater/recipe/pull/832#pullrequestreview-980528419
- [ ] update cookbook responsive carousel image
- [ ] add cookbook responsive carousel related components section
- [ ] rebase and conflicts
- [ ] base branch on v15
- [ ] update v15 migration guide

2022-05-20 19:28 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/utils.tsx
> +    if you change the sizes, then the card/images heights get weird */
added to do list below

2022-05-20 19:29 UTC, danidewitt commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/utils.tsx
> +};
added to do list below

2022-06-16 21:29 UTC, noranda approved these changes

2022-06-17 15:29 UTC, pgrippi commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +    }, [calculateDesktopCardWidth, calculateMobileCardWidth, calculateNumCardsPerPage]);
This is good but `calculateDesktopCardWidth` will change as the number of cards changes, which will cause you to teardown and recreate the `resize` listener

It looks like there are really only two or three pieces of state we actually care about: the window `innerWidth`, the size of the container, and whether or not to show the mobile view (which is driven by the `innerWidth`)

I think you could simplify this a little bit by not using callbacks but instead using `ResizeObserver` to check for changes in content width and calculating the number of cards / card with on render, as it'll be a very straightforward check

I'm thinking something like this (I have not tested this at all):

```jsx
// these are the pieces of state you really care about
const [showMobile, setShowMobile] = useState(false);
const [page, setPage] = useState(1);
const [containerSize, setContainerSize] = useState(0);

// this will be the container the `ResizeObserver` monitors
const containerRef = useRef(null);

// the `typeof` check will allow this to work during SSR where `ResizeObserver` won't be defined
const observer = useRef(
  typeof ResizeObserver !== 'undefined'
    ? new ResizeObserver(entries => {
        // Only care about the first element, we expect one element ot be watched
        const [entry] = entries;

        if (entry.contentBoxSize) {
          // Firefox implements `contentBoxSize` as a single content rect, rather than an array
          const contentBoxSize = Array.isArray(entry.contentBoxSize)
            ? entry.contentBoxSize[0]
            : entry.contentBoxSize;
          setContainerSize(contentBoxSize.inlineSize);
        } else {
          // older browsers use `contentRect`
          setContainerSize(entry.contentRect.width);
        }
      })
    : null
);

// this remains mostly the same, monitoring the window resize and setting the `showMobile` state appropriately
useEffect(() => {
  const handleResize = () => {
    setShowMobile(window.innerWidth < 768);
  };

  window.addEventListener('resize', handleResize, {passive: true});
  return () => window.removeEventListener('resize', handleResize);
}, []);

// this hooks up the ResizeObserver to the container
useEffect(() => {
  if (containerRef.current) {
    observer.current.observe(containerRef.current);
  }

  return () => {
    observer.current.unobserve();
  };
}, [containerRef, observer]);

// these used to be pieces of state, now they are calculated on render
const numCardsPerPage = containerSize > 1024 ? 4 : containerSize > 650 ? 3 : 2;
const carouselPadding = CARD_SPACING * (numCardsPerPage - 1);
const desktopCardWidth =
  containerSize === 0
    ? '240px'
    : `${Math.ceil((containerSize - carouselPadding) / numCardsPerPage)}px`;
const mobileCardWidth = containerSize > 430 ? '280px' : '240px';
```

2022-06-17 17:06 UTC, noranda commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +    }, [calculateDesktopCardWidth, calculateMobileCardWidth, calculateNumCardsPerPage]);
Good catch! I like the idea of using `ResizeObserver`, but would rather use a hook for this, so I've refactored this to do so. Tested and everything works as expected!

2022-06-17 17:10 UTC, noranda commented on packages/recipe/src/components/EzCarousel/Implementations/EzCarouselCustom/EzCarouselCustom.tsx
> +    );
I like it!

2022-06-17 17:33 UTC, pgrippi approved these changes

2022-06-22 20:50 UTC, noranda commented
Based on a conversation with @ktlnux, the following changes were made:

1. Added a `12px` right margin to the title to make sure we don't overcrowd the buttons.
2. Fixed an issue where the `EzCard` drop shadows was cut off by adding a `1px` margin.
3. Fixed an issue where the `EzCard` border radius was `0` at mobile sizes.
4. Added a horizontal margin to the header, buttons, and card container to imitate a "bleed" behavior when horizontal scrolling on mobile viewports. Note that this does not actually bleed into the parent container and therefore will need to have `0` horizontal padding/margin in order to effect a bleed to the edge of the viewport as shown in the [design](https://www.figma.com/proto/bgAAENXKvEh36UMykJ2v7T/Marketplace-Web?page-id=757%3A15893&node-id=1135%3A33103&viewport=1207%2C-5365%2C0.35&scaling=min-zoom&starting-point-node-id=1135%3A33103&show-proto-sidebar=1).

Note: There is a localized issue in the Playroom where the new images added in this PR do not load. This is because the playroom grabs these images from the live doc site, and until this PR is merged and released, these images don't yet exist there. This should not be an issue once released.

2022-06-22 21:40 UTC, merged