Pac 1922 fix a11y date time
ezcater/recipe pull request #837
Opened 2022-06-08 17:46 UTC by ghulam-murtaza-ez

## What did we change?
Fix accessibility issue with Date and Time fields
## Why are we doing this?
There was accessibility issue with Date and Time fields
## Screenshot(s) / Gif(s):

## Checklist

- [ ] Provide test coverage for the changes made
- [x] Create a changeset (`yarn changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2022-06-08 17:59 UTC, onocy commented
Could you explain a bit how this fixes the android swiping issue mentioned in the original ticket?

2022-06-09 12:33 UTC, ghulam-murtaza-ez commented
>

2022-06-09 12:46 UTC, ghulam-murtaza-ez commented
> swiping

The issue was with the opening of the Date/Time select popups. Once opened the left/right/up/down swipe are already working for navigation through the Date/Time fields. I made it so that the Date/time can be opened via accessibility controls as well.

2022-06-09 12:52 UTC, evan-007 commented on packages/recipe/src/components/Overlays.ts
> +    Enter: state.open,
could we add a test for this change?

2022-06-09 18:56 UTC, onocy commented on packages/recipe/src/components/EzField/__tests__/EzField.time.test.tsx
> +    keyDown('Enter');
🎱 Can we just have this inline like the other test since we don't use `keyDown` elsewhere in this block?

2022-06-09 18:56 UTC, onocy approved these changes

2022-06-10 13:31 UTC, onocy submitted a review, later dismissed

2022-06-10 13:35 UTC, evan-007 approved these changes

2022-06-10 13:35 UTC, evan-007 commented on .changeset/chilled-panthers-breathe.md
> +Fix a11y for Date and Time fields
could we add some more details here? maybe `Accessibility fix: Allow 'Enter' keypresses to open EzField type='datepicker'`

2022-06-10 14:28 UTC, onocy submitted a review, later dismissed

2022-06-10 14:28 UTC, evan-007 submitted a review, later dismissed

2022-06-10 14:38 UTC, danidewitt approved these changes
thanks for adding tests!

2022-06-10 14:43 UTC, danidewitt requested changes
@noranda is looking at related issues with this change - please don't merge until you get her approval

2022-06-10 14:55 UTC, noranda requested changes
This change affects not just date and time inputs, but also `EzAutosuggest`, and `EzSelect`, which also uses `menuTriggerProps`. I think it makes sense to have Enter open the selects, but could you add additional tests for `EzAutosuggest` and `EzSelect` for consistency? Otherwise this looks good! Thanks!

2022-06-10 14:55 UTC, noranda commented on .changeset/chilled-panthers-breathe.md
> +Accessibility fix: Allow 'Enter' keypresses to open EzField type='date' and type='time'
Recipe has a [versioning guide](https://ezcater.github.io/recipe/guides/versioning-and-changelog) to help with changelog descriptions. In this case, I might edit to:
```suggestion
fix: add 'Enter' keypress to open EzField inputs (date, time, select, autosuggest) for better accessibility
```

2022-06-10 17:10 UTC, noranda commented
@ghulam-murtaza-ez I'm getting a broken test with autosuggest. Can you confirm and/or fix?

2022-06-13 11:50 UTC, ghulam-murtaza-ez commented
> @ghulam-murtaza-ez I'm getting a broken test with autosuggest. Can you confirm and/or fix?

I have fixed the broken test, my lint is passing locally but somehow it is failing during actions. There is some issue with Node.js setup

2022-06-13 12:31 UTC, noranda commented
> I have fixed the broken test, my lint is passing locally but somehow it is failing during actions. There is some issue with Node.js setup

I can confirm everything passes locally. It looks like GitHub is experiencing [degradation](https://www.githubstatus.com/) with Actions right now. Hopefully this will be resolved soon! Once we merge it'll run other actions so let's hold off merging for now.

2022-06-13 14:10 UTC, noranda approved these changes
Looks great! Thanks for your contribution!

2022-06-13 14:45 UTC, danidewitt approved these changes

2022-06-13 15:01 UTC, merged