radio group
ezcater/recipe pull request #844
Opened 2022-06-22 15:06 UTC by ez-alexfrazer

## What did we change?

- Adds `EzRadioGroup` component

## Why are we doing this?

- Increase number of form components

## Screenshot(s) / Gif(s):

## Checklist

- [x] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2022-06-29 17:38 UTC, noranda requested changes
Initial comments below.

2022-06-29 17:38 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/EzRadioGroup.md
> +---
Remove file but include documentation for it in `EzRadio`.

2022-06-29 17:38 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/EzRadioGroup.preview.md
> +```jsx
Remove file.

2022-06-29 17:38 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/EzRadioGroup.tsx
> +EzRadioGroup.defaultProps = {};
Remove line.

2022-06-29 17:38 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/Implementations/EzRadioGroupImplementation.tsx
> +const EzRadioGroupImplementation = forwardRef<Ref, EzRadioGroupProps>((props, ref) => {
Rename component `EzRadioGroupMui`.

2022-06-29 17:38 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/Implementations/EzRadioGroupImplementation.tsx
> +import React, {forwardRef} from 'react';
Keep this import on top.

2022-06-29 17:38 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/Implementations/EzRadioGroupImplementation.tsx
> +EzRadioGroupImplementation.defaultProps = {};
Remove line.

2022-06-29 17:38 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/__tests__/EzRadioGroup.test.tsx
> +import {visualSnapshots} from 'sosia';
Remove line and all sosia related testing in this file.

2022-06-29 17:38 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/__tests__/EzRadioGroup.test.tsx
> +  it('should have tests', () => {});
Add tests or remove.

2022-06-29 17:38 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/__tests__/EzRadioGroup.test.tsx
> +  });
Add type checking or remove.

2022-07-05 20:47 UTC, noranda approved these changes
Looks good, just needs a rebase!

2022-07-11 13:50 UTC, noranda approved these changes

2022-07-12 18:28 UTC, danidewitt commented on packages/recipe/src/components/EzRadioGroup/EzRadioGroup.tsx
> +const EzRadioGroup = forwardRef<Ref, EzRadioGroupProps>((props, ref) => {
do we want to be more explicit about some of the props we pass into this component? i'm thinking some of them should be, especially if we ever have other implementations (or if mui changes) @ez-alexfrazer @noranda

2022-07-12 18:30 UTC, danidewitt commented on packages/recipe/src/components/index.ts
> +export {default as EzRadioGroup} from './EzRadioGroup';
are we going to expose this on the component grid? are we going to add documentation? does that also require a preview image? @noranda

2022-07-12 18:43 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/EzRadioGroup.tsx
> +const EzRadioGroup = forwardRef<Ref, EzRadioGroupProps>((props, ref) => {
Not a bad idea to keep things in scope. @ez-alexfrazer I would look into which props you need to support for `EzRadio` and only include those. You can see how I did the same thing in [`EzChip`](https://github.com/ezcater/recipe/blob/main/packages/recipe/src/components/EzChip/EzChip.tsx#L6) to limit what props get passed in.

2022-07-12 18:43 UTC, noranda commented on packages/recipe/src/components/index.ts
> +export {default as EzRadioGroup} from './EzRadioGroup';
We don't want to expose this on the component grid because it's a util component, only used to support other components like `EzRadio`.

2022-08-02 19:44 UTC, noranda commented on .changeset/clever-mayflies-play.md
> +[feat] adds RadioGroup component
```suggestion
feat: adds RadioGroup component
```

2022-08-02 20:01 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/EzRadioGroup.tsx
> +const EzRadioGroup = forwardRef<Ref, EzRadioGroupProps>((props, ref) => {
@ez-alexfrazer Let's keep this simple and start with `children` as the only prop for this PR. If we need to add props (like `aria-labelledby`, `defaultValue`, `name`, `onChange`, `row`, or `value`) later as part of `EzRadio`, we can do that then. It's a lot easier to add a prop than remove one.

EzRadioGroup.jsx:
```js
...
const EzRadioGroup = forwardRef<Ref, EzRadioGroupProps>(({children}, ref) => (
  <EzRadioGroupMui ref={ref}>{children}</EzRadioGroupMui>
));
...
```

EzRadioGroupMui.tsx:
_Note: passing in `...props` in the implementation allows us to keep this the same if/when we add additional props to the explicit top level component._
```js
...
const EzRadioGroupMui = forwardRef<Ref, EzRadioGroupProps>(({children, ...props}, ref) => (
  <RadioGroup {...props} ref={ref}>
    {children}
  </RadioGroup>
));
...
```

EzRadioGroup.types.ts:
```js
...
export interface EzRadioGroupProps {
  children: ReactNode;
}
...
```

EzRadioGroup.test.tsx:
```js
...
const Component: FC<Partial<ComponentProps<typeof EzRadioGroup>>> = ({children}) => (
  <EzRadioGroup>{children}</EzRadioGroup>
);
...
```

2022-08-10 16:58 UTC, noranda commented on packages/recipe/src/components/EzRadioGroup/EzRadioGroup.tsx
> +const EzRadioGroup = forwardRef<Ref, EzRadioGroupProps>((props, ref) => {
Changes pushed.

2022-08-10 16:59 UTC, noranda commented on .changeset/clever-mayflies-play.md
> +[feat] adds RadioGroup component
Changes pushed.

2022-08-10 17:06 UTC, noranda submitted a review, later dismissed

2022-08-16 19:32 UTC, danidewitt approved these changes

2022-08-17 13:06 UTC, noranda approved these changes

2022-08-17 13:07 UTC, merged