feat: add icons, icon buttons, and tooltips to table header column prop
ezcater/recipe pull request #916
Opened 2023-03-14 18:23 UTC by danidewitt

## What did we change?
- Added new type to table column prop to allow the use of `EzIcon`, `EzIconButton`, `EzTooltip`, with corresponding tests and documentation

## Why are we doing this?
- Designer request

## Screenshot(s) / Gif(s):
<img width="652" alt="Screen Shot 2023-03-14 at 2 21 58 PM" src="https://user-images.githubusercontent.com/3790037/225101531-e6190a17-c6cb-4e72-97d5-6918898d262a.png">

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2023-03-14 18:25 UTC, pgrippi approved these changes

2023-03-14 18:26 UTC, pgrippi commented on packages/recipe/src/components/EzTable/EzTable.tsx
> +                {heading} {icon && <span className={headerIcon()}>{icon}</span>}{' '}
is the space (`{' '}`) needed with the `gap` property applied here? or is it just to give it some extra spacing?

2023-03-14 19:03 UTC, danidewitt commented on packages/recipe/src/components/EzTable/EzTable.tsx
> +                {heading} {icon && <span className={headerIcon()}>{icon}</span>}{' '}
i didn't add it on purpose - it got auto-added on save

2023-03-14 19:05 UTC, pgrippi commented on packages/recipe/src/components/EzTable/EzTable.tsx
> +                {heading} {icon && <span className={headerIcon()}>{icon}</span>}{' '}
ahhh I love when prettier does that!

2023-03-15 21:18 UTC, noranda requested changes
Do we need to support `EzIconButton` here? I only ask because I don't see it in the design and it does create a bit of UX confusion when paired with sortable headers, since you now have two separate onClicks happening in the same area. Would we be ok just supporting `EzIcon` with a tooltip?

2023-03-16 14:24 UTC, noranda commented
Also, the `EzIconButton` and sort icon aren't showing up in the playroom (the opacity is `0`).
<img width="807" alt="Screenshot 2023-03-16 at 10 23 01 AM" src="https://user-images.githubusercontent.com/5418735/225647169-8547e84d-94f3-40be-920d-6d1232fd6652.png">

2023-03-17 15:03 UTC, paul-ez approved these changes

2023-03-17 15:37 UTC, danidewitt commented
i added `EzIconButton` because it was in the ticket, but i'm definitely in favor of removing it

2023-03-17 17:59 UTC, noranda approved these changes
Approved with typo fix. It might also be good to update the PR description here. Nice work!

2023-03-17 17:59 UTC, noranda commented on packages/recipe/src/components/EzTable/EzTable.md
> +Consider and choose the appropriate the size, color, and accessibility of each icon added to table column headers in the context of the rest of the columns.
```suggestion
Consider and choose the appropriate size, color, and accessibility of each icon added to table column headers in the context of the rest of the columns.
```

2023-03-17 18:12 UTC, pgrippi approved these changes

2023-03-20 16:08 UTC, paul-ez approved these changes

2023-03-27 15:46 UTC, merged