feat: add title icon to EzTable
ezcater/recipe pull request #918
Opened 2023-03-14 20:16 UTC by danidewitt

## What did we change?
- Added heading icon titleIcon prop to EzTable
- ⚠️ Should be merged into https://github.com/ezcater/recipe/pull/917 before merging https://github.com/ezcater/recipe/pull/917

## Why are we doing this?
- Design request

## Screenshot(s) / Gif(s):
<img width="649" alt="Screen Shot 2023-03-14 at 4 15 25 PM" src="https://user-images.githubusercontent.com/3790037/225126028-c78d8a8a-43e2-484b-9fa2-e35c6292eea9.png">

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2023-03-16 13:45 UTC, paul-ez approved these changes

2023-03-16 15:31 UTC, noranda requested changes
This has the same issue as PR #917 where the layout of tables with actions has broken:

Current:
<img width="636" alt="Screenshot 2023-03-16 at 11 28 30 AM" src="https://user-images.githubusercontent.com/5418735/225666649-2616c8c5-0aac-457a-9ae6-7eddaf6050d1.png">

This PR:
<img width="637" alt="Screenshot 2023-03-16 at 11 28 14 AM" src="https://user-images.githubusercontent.com/5418735/225666722-2b821477-aef9-402b-bf4b-4246e16b3839.png">

2023-03-16 15:31 UTC, noranda commented on packages/recipe/src/components/EzTable/EzTable.md
>  Used whenever the tabular data alone represents a cohesive set of content. Should be used with a `title` prop and may include optional actions.
Should we mention the new `titleIcon` prop here?

2023-03-16 15:31 UTC, noranda commented on packages/recipe/src/components/EzTable/EzTable.tsx
> +    <EzCard title={title} subtitle={subtitle} actions={actions} titleIcon={titleIcon || null}>
I think we can leave out the `|| null` here as it will be `undefined` if not provided.
```suggestion
    <EzCard title={title} subtitle={subtitle} actions={actions} titleIcon={titleIcon}>
```

2023-03-17 17:20 UTC, danidewitt commented
this has the same issue as the other PR because it's based off the branch of the other PR, as noted in the PR description

2023-03-17 19:08 UTC, noranda approved these changes
🚀

2023-03-27 16:16 UTC, merged