feat: add globalFilter and disableGlobalFilter props to EzTable
ezcater/recipe pull request #925
Opened 2023-03-16 14:50 UTC by danidewitt

## What did we change?
- Add `globalFilter` and `disableGlobalFilter` to `EzTable`

## Why are we doing this?
- Designer request

## Screenshot(s) / Gif(s):
<img width="521" alt="Screen Shot 2023-03-16 at 10 50 29 AM" src="https://user-images.githubusercontent.com/3790037/225655287-f37ae77d-ad40-4441-bcf0-70d4188840da.png">

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2023-03-16 15:33 UTC, paul-ez submitted a review, later dismissed

2023-03-17 15:44 UTC, noranda requested changes
A few things here. Could we change `globalFilter` to `filterTerm`? I think the word "global" is a bit confusing (is there a local filter?) and "term" makes it more clear it's a string that you're filtering by. Also, I think we can get rid of `disableGlobalFilter` entirely and let the users define the logic on their own. For example:

```js
() => {
  const [searchTerm, setSearchTerm] = React.useState('');
  const items = [
    {id: '#004', date: '02/28/18', total: '$3267', name: 'Tacodeli'},
    {id: '#005', date: '02/28/18', total: '$3214', name: 'Torchys'},
    {id: '#006', date: '03/01/18', total: '$6212', name: 'Tacobell'},
    {id: '#007', date: '04/10/18', total: '$2219', name: 'Chipotle'},
    {id: '#008', date: '05/13/18', total: '$2713', name: 'Naco Taco'},
  ];
  const disableFilter = items.length > 5;
  const searchInput = (
    <EzSearchInput
      placeholder="Search"
      aria-label="Search orders"
      value={searchTerm}
      onChange={e => setSearchTerm(e.target.value)}
      disabled={disableFilter}
    />
  );
  return (
    <EzPage>
      <EzTable
        title="All Orders"
        actions={searchInput}
        filterTerm={disableFilter ? null : searchTerm}
        columns={[
          {heading: 'Order number', key: 'id'},
          {heading: 'Event date', key: 'date'},
          {heading: 'Total', key: 'total', numeric: true},
          {heading: 'Name', key: 'name'},
        ]}
        items={items}
      />
    </EzPage>
  );
};
```

Thoughts?

(This also needs to be rebased to `v17`.)

2023-03-17 15:44 UTC, noranda commented on packages/recipe/src/components/EzTable/EzTable.md
> +If the globabl filter needs to be disabled for backend pagniation purposes, use the `disableGlobalFilter` prop.
Typo.
```suggestion
If the global filter needs to be disabled for backend pagniation purposes, use the `disableGlobalFilter` prop.
```

2023-03-27 20:28 UTC, danidewitt commented
@noranda please see https://react-table-v7.tanstack.com/docs/api/useGlobalFilter#table-options for why i chose global filter and disable global filter

2023-03-27 20:48 UTC, noranda commented
> @noranda please see https://react-table-v7.tanstack.com/docs/api/useGlobalFilter#table-options for why i chose global filter and disable global filter

Ah ok, but do we need to have the same API as React Table? I still think the disable prop is not needed here.

2023-03-30 17:29 UTC, merged