feat: add onKeyDown to options in EzSegmentedControl
ezcater/recipe pull request #944
Opened 2023-05-05 19:27 UTC by danidewitt

## What did we change?
- Added `onKeyDown` to `options` prop for `EzSegmentedControl` with relevant documentation and tests

## Why are we doing this?
- Allow better keyboard selection and deselection (accessibility)

## Screenshot(s) / Gif(s):
<img width="646" alt="Screen Shot 2023-05-05 at 3 25 39 PM" src="https://user-images.githubusercontent.com/3790037/236551757-1cd506cb-c482-44ec-b2f2-350e9dd69444.png">

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2023-05-05 19:35 UTC, pgrippi commented on packages/recipe/src/components/EzSegmentedControl/EzSegmentedControl.tsx
> +          onKeyDown={() => option.onKeyDown && option.onKeyDown(option.value)}
would it make more sense to pass the event on `onKeyDown`? something like:

```tsx
onKeyDown={event => options.onKeyDown?.(event, value)}
```

I think consumers like store-next are going to way to know what key was pressed, to react accordingly.

2023-05-05 19:46 UTC, pgrippi commented on packages/recipe/src/components/EzSegmentedControl/EzSegmentedControl.md
> +        name="view-map-options-with-onclick-option"
I think this needs a different name, it's connected to the example above it:

https://user-images.githubusercontent.com/1180841/236555349-4772f06e-83e0-436e-8154-5c7caacf15e1.mp4

2023-05-05 20:04 UTC, pgrippi commented
I think ecomm is looking for the ability to use tab and keyboard controls like enter/space to change the options. using `onKeyDown` on the options themselves will allow us to change the value when enter/space is used, but tabbing between the options doesn't work.

@amberlcook after playing around with this component I noticed that the arrow keys are used to change the active value:

https://user-images.githubusercontent.com/1180841/236557534-488b42dc-2c80-4f32-b9fb-3702b9711881.mp4

I think that's why we can't tab between the elements - we're not supposed to!

so with that in mind:

1. since we can change the value using left+right, is that fine for accessibility? I imagine this component was designed with that interface in mind so maybe we were just testing it wrong?
2. if not, maybe having an `isTabbable` option on `EzSegmentedControl` would be a better interface? then we don't need to intercept keydown, it will just change the behavior internally in recipe to be tabable buttons instead of one "button group"

2023-05-05 20:09 UTC, danidewitt commented
@pgrippi i already had put that information about the guidance on tab vs. arrows in the documentation and the slack thread

2023-05-05 20:11 UTC, danidewitt commented on packages/recipe/src/components/EzSegmentedControl/EzSegmentedControl.md
> +        name="view-map-options-with-onclick-option"
nice catch, i used the previous example as a template

2023-05-05 20:12 UTC, danidewitt commented on packages/recipe/src/components/EzSegmentedControl/EzSegmentedControl.tsx
> +          onKeyDown={() => option.onKeyDown && option.onKeyDown(option.value)}
hm, i can be convinced, but why would do we need to know which key

2023-05-05 20:15 UTC, pgrippi commented on packages/recipe/src/components/EzSegmentedControl/EzSegmentedControl.tsx
> +          onKeyDown={() => option.onKeyDown && option.onKeyDown(option.value)}
well the way it is now, if the user hits any key on the keyboard it'll toggle off the value, I think we only want certain keys to toggle the value

2023-05-08 13:33 UTC, noranda requested changes
There are two issues here that I think need to be addressed:

1. The focus outline on an unselected option is not closed. It looks fine for selected options.
<img width="580" alt="Screenshot 2023-05-08 at 9 25 06 AM" src="https://user-images.githubusercontent.com/5418735/236836809-bdcd3bb0-2f23-41b5-b2a3-242aa9cdde82.png">
<img width="583" alt="Screenshot 2023-05-08 at 9 29 03 AM" src="https://user-images.githubusercontent.com/5418735/236836882-a45cff4d-b7f9-4c51-a8fe-4b96e8546ff8.png">

2. The keyboard selection behavior works fine for "enter", but not for "space", which will both unselect and then reselect an option.
https://user-images.githubusercontent.com/5418735/236837800-ae1ea9f7-f7c8-4024-bf55-69be4db1bf1e.mp4

2023-05-08 16:45 UTC, danidewitt commented
@noranda seems to be a pre-existing styling issue

2023-05-08 16:49 UTC, pgrippi approved these changes

2023-05-08 18:00 UTC, amberlcook approved these changes
This looks great!! Thanks so much for working on this so quickly.

2023-05-08 18:35 UTC, noranda approved these changes

2023-05-08 18:38 UTC, merged