feat: add EzBarChart component
ezcater/recipe pull request #958
Opened 2023-05-16 18:06 UTC by danidewitt

## What did we change?
- Add `EzBarChart` component

## Why are we doing this?
- Design request

## Screenshot(s) / Gif(s):
<img width="482" alt="Screen Shot 2023-05-16 at 1 58 25 PM" src="https://github.com/ezcater/recipe/assets/3790037/69c68906-795a-4c53-a1eb-3a07c9880e8d">
<img width="879" alt="Screen Shot 2023-05-16 at 1 58 47 PM" src="https://github.com/ezcater/recipe/assets/3790037/8901cf6a-2913-4bcf-a628-a02b3442e46e">
<img width="534" alt="Screen Shot 2023-05-16 at 1 58 53 PM" src="https://github.com/ezcater/recipe/assets/3790037/30a5522d-5631-46b4-9ea4-174424ea7d34">
<img width="538" alt="Screen Shot 2023-05-16 at 1 59 00 PM" src="https://github.com/ezcater/recipe/assets/3790037/ac6a298e-b675-4cdb-85b4-01c5d9ec4cd2">
<img width="1430" alt="Screen Shot 2023-05-16 at 2 04 16 PM" src="https://github.com/ezcater/recipe/assets/3790037/03c73bca-f6fe-4dc9-a087-d3825b238a80">

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2023-05-18 19:44 UTC, noranda requested changes
Nice job! Just a few documentation comments, otherwise this looks good to me.

You'll also need to run `yarn install` on the root as there are changes.

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +Bar charts are a [type of chart](<(https://help.flourish.studio/article/25-line-bar-and-pie-charts)>) consisting of a series of bars that describe a dataset.
This link doesn't work.
```suggestion
Bar charts are a [type of chart](https://help.flourish.studio/article/25-line-bar-and-pie-charts) consisting of a series of bars that describe a dataset.
```

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +- Bar charts are good for comparing relative size
This is certainly fine for now, but do we want to reach out to UX content about what this should include for our design system?

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +Bar charts should include a title and container in an `EzCard` container, the title can optionally have a description and icon.
```suggestion
Bar charts should include a title and be contained in an `EzCard`. The title can optionally have a description and icon.
```

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +To chart a data set as a bar chart, provide a dataset as a `data` array of objects with `x` and `y` values, for example: `data = [{x: 'first', y: 1}, {x: 'second', y: 2}, {x: 'third', y: 3}]`
Perhaps this can be formatted to be easier to read?

---

To create a bar chart, provide a data set as a `data` array of objects with `x` and `y` values. For example:

```js
data = [
  {x: 'first', y: 1},
  {x: 'second', y: 2},
  {x: 'third', y: 3},
];
```

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +Always provide `title` and a detailed `description` for assistive devices.
I would move this to an "Accessibility" section near the bottom to match our other component docs.

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +    {x: 'Decemeber', y: 180000},
```suggestion
    {x: 'December', y: 180000},
```

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +Bar colors can be customized with [theme colors](http://localhost:8000/guides/theming/#colors), the default is `primary`.
Should this be in a separate "Bar Chart Colors" section to match our other component doc pages?

```suggestion
Bar colors can be customized with [theme colors](/guides/theming/#colors). The default color is `primary`.
```

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +If your dataset may sometimes be an empty array, work with design to render something other than a blank chart, perhaps an `EzBlankState`.
```suggestion
If your data set may sometimes be an empty array, work with design to render something other than a blank chart, perhaps an [`EzBlankState`](/components/ez-blank-state).
```

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +    },
I would put any required props at the top, in alphabetical order.

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +    },
Place required props at the top, in alphabetical order.

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +      types: ['array of axis label values'],
```suggestion
      types: ['AxisLabelValue[]'],
```

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +      types: ['array of axis label values'],
```suggestion
      types: ['AxisLabelValue[]'],
```

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +      types: ['array of datum'],
```suggestion
      types: ['Datum[]'],
```

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +      types: ['function'],
For consistency with our other component docs.
```suggestion
      types: ['func'],
```

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +      types: ['function'],
For consistency with our other component docs.
```suggestion
      types: ['func'],
```

2023-05-18 19:44 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +- [Progress](/components/ez-progress)
```suggestion
- [EzProgress](/components/ez-progress)
- [EzBlankState](/components/ez-blank-state)
```

2023-05-18 21:15 UTC, danidewitt commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +- Bar charts are good for comparing relative size
sure. i was trying to get this out quickly without another design loop since they needed it earlier this week

2023-05-18 21:20 UTC, danidewitt commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +Always provide `title` and a detailed `description` for assistive devices.
it's part of the required props though?

2023-05-18 21:21 UTC, danidewitt commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +    {x: 'Decemeber', y: 180000},
i fixed this in https://github.com/ezcater/recipe/pull/961

2023-05-18 21:26 UTC, danidewitt commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +    },
this is in alphabetical order, to match the props passed between the components

2023-05-18 21:26 UTC, danidewitt commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +    },
this is in alphabetical order, to match the props passed between the components

2023-05-19 13:29 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +    {x: 'Decemeber', y: 180000},
Could we fix it in this PR as well? I think it's better to keep reviews and review fixes to their respective PRs, then just rebase any PRs based on it after. It keeps everything clean IMO, but up to you.

2023-05-19 16:35 UTC, danidewitt commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +    {x: 'Decemeber', y: 180000},
the bar chart PR was first, so line chart should be merged into it?

2023-05-19 17:20 UTC, noranda commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> +    {x: 'Decemeber', y: 180000},
I mean we can do it this way for this set of PRs if you like, but in general I think it's better practice to go the other way. Merge PRs in the order they're opened and then rebase anything based on them after the merge. This means you can keep working without worry that something you're working on now that's based off older work must get merged first. I would not be able to do it that way with the Storybook Docs work for instance. It also keeps all the code and reviews clean and relevant for that particular PR, not spread across PRs. We can talk about it more offline if you want!

2023-05-19 17:33 UTC, noranda approved these changes

2023-05-19 17:56 UTC, merged