feat: add EzLineChart component
ezcater/recipe pull request #959
Opened 2023-05-16 18:06 UTC by danidewitt

## What did we change?
- Add `EzBarChart` component

## Why are we doing this?
- Design request

## Screenshot(s) / Gif(s):
<img width="792" alt="Screen Shot 2023-05-16 at 2 03 17 PM" src="https://github.com/ezcater/recipe/assets/3790037/a18de5bb-cf7c-414f-813e-50a78f279e6f">
<img width="859" alt="Screen Shot 2023-05-16 at 2 03 36 PM" src="https://github.com/ezcater/recipe/assets/3790037/f35bf289-b684-4db1-9b0c-c2564ddf45bf">
<img width="513" alt="Screen Shot 2023-05-16 at 2 03 42 PM" src="https://github.com/ezcater/recipe/assets/3790037/2e2b9db9-f9f9-4e15-b51e-008682e4209f">
<img width="514" alt="Screen Shot 2023-05-16 at 2 03 50 PM" src="https://github.com/ezcater/recipe/assets/3790037/7349ed0a-81a0-4e0f-b49f-386e5dc140e6">
<img width="1415" alt="Screen Shot 2023-05-16 at 2 04 38 PM" src="https://github.com/ezcater/recipe/assets/3790037/9cf65d2b-c85f-4ab3-988f-90972d114016">

## Checklist

- [ ] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2023-05-16 20:25 UTC, agrobbin commented on packages/recipe/src/components/EzLineChart/EzLineChart.types.ts
> +  y: number | number;
Do we need `number | number` here, or can `number` suffice?

2023-05-16 20:27 UTC, agrobbin commented on packages/recipe/src/components/EzLineChart/EzLineChart.types.ts
> +  x: string | number;
Does this limit our flexibility at all? When I think of charts and X-axis data specifically, I expect it to be any number of different types of data (dates, times, numbers, string, etc.). Would we be better off if we were ignorant of the X-axis value type?

2023-05-16 20:48 UTC, danidewitt commented on packages/recipe/src/components/EzLineChart/EzLineChart.tsx
> +      independentAxisLabelValues={independentAxisLabelValues}
yeah, you can have a bar chart display horizontally: https://formidable.com/open-source/victory/docs/victory-bar#horizontal. while we're not doing that in this chart *yet*, i'd prefer not to start with x and y and then later need to make breaking changes to prop names because we want to use `horizontal` bar charts... which i can predict we'll want in a few weeks once people realize we have charting capabilities

2023-05-16 20:49 UTC, danidewitt commented on packages/recipe/src/components/EzLineChart/EzLineChart.types.ts
> +type Datum = {
is this real feedback about my variable name or a joke

2023-05-16 20:49 UTC, danidewitt commented on packages/recipe/src/components/EzLineChart/EzLineChart.types.ts
> +  y: number | number;
well that should be `string | number` i think - good catch

2023-05-16 20:50 UTC, danidewitt commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +- Line charts are used to a changing time series
i grabbed it from an external resource actually. i can add a link. we have best practices at the top of all our components, usually source this from designers and a mix of external resources

2023-05-16 20:54 UTC, danidewitt commented on packages/recipe/src/components/EzLineChart/EzLineChart.types.ts
> +  x: string | number;
ah, i thought i read in the victory docs it was limited, but now i can't seem to find it. i'll dig around a little more just to make sure.

2023-05-17 12:31 UTC, agrobbin commented on packages/recipe/src/components/EzLineChart/EzLineChart.types.ts
> +type Datum = {
Definitely a joke. 😆

2023-05-17 12:45 UTC, agrobbin approved these changes
Just 1 other question from me!

2023-05-17 12:45 UTC, agrobbin commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +  );
Do we need a header icon to get our point across with this example? If we can simplify the code samples down to their bare minimums, I'd imagine we make users more comfortable using our components.

2023-05-18 20:17 UTC, noranda requested changes
It looks like you made some changes in your EzBarChart PR and then made the same changes here instead of rebasing. That's a bit confusing when reviewing both. Could you rebase this one on your other branch instead? That should remove these changes. Otherwise, looks good!

You'll also need to run yarn install on the root as there are changes.

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +To chart a data set as a line chart, provide a dataset as a `data` array of objects with `x` and `y` values, for example: `data = [{x: 'first', y: 1}, {x: 'second', y: 2}, {x: 'third', y: 3}]`
Perhaps this can be formatted to be easier to read?

---

To create a line chart, provide a data set as a `data` array of objects with `x` and `y` values. For example:

```js
data = [
  {x: 'first', y: 1},
  {x: 'second', y: 2},
  {x: 'third', y: 3},
];
```

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +Always provide `title` and a detailed `description` for assistive devices.
I would move this to an "Accessibility" section near the bottom to match our other component docs.

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +    {x: 'Decemeber', y: 3500},
```suggestion
    {x: 'December', y: 3500},
```

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +Lines colors can be customized with [theme colors](http://localhost:8000/guides/theming/#colors), the default is `primary`.
Should this be in a separate "Line Chart Colors" section to match our other component doc pages?

```suggestion
Line colors can be customized with [theme colors](/guides/theming/#colors). The default color is `primary`.
```

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +If your dataset may sometimes be an empty array, work with design to render something other than a blank chart, perhaps an `EzBlankState`.
```suggestion
If your data set may sometimes be an empty array, work with design to render something other than a blank chart, perhaps an [`EzBlankState`](/components/ez-blank-state).
```

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +      types: ['array of datum'],
```suggestion
      types: ['Datum[]'],
```

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +      types: ['function'],
For consistency with our other component docs.
```suggestion
      types: ['func'],
```

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +      types: ['function'],
For consistency with our other component docs.
```suggestion
      types: ['func'],
```

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +      types: ['array of axis label values'],
```suggestion
      types: ['AxisLabelValue[]'],
```

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +      types: ['array of axis label values'],
```suggestion
      types: ['AxisLabelValue[]'],
```

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +    },
I would put any required props at the top, in alphabetical order.

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +- [Progress](/components/ez-progress)
```suggestion
- [EzBarChart](/components/ez-bar-chart)
- [EzProgress](/components/ez-progress)
- [EzBlankState](/components/ez-blank-state)
```

2023-05-18 20:17 UTC, noranda commented on packages/recipe/src/components/EzLineChart/__tests__/EzLineChart.test.tsx
> +import {axe} from '../../../../test-utils';
In order for the tests to use themes correctly, we need to import `render` from our `test-utils` file. Probably not an issue here, but if we add any theme-related tests in the future, it will be.

```suggestion
import {axe, render} from '../../../../test-utils';
```

2023-05-18 20:45 UTC, danidewitt commented on packages/recipe/src/components/EzBarChart/EzBarChart.md
> -
yeah i accidentally did it in this one because that's where alex brought it up - this is getting merged into that branch anyway

2023-05-18 20:46 UTC, danidewitt commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +Always provide `title` and a detailed `description` for assistive devices.
it's part of the required props though?

2023-05-18 20:47 UTC, danidewitt commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +    },
yeah, i wrote these in alphabetical order

2023-05-19 13:42 UTC, noranda commented on packages/recipe/src/components/EzLineChart/EzLineChart.md
> +    },
It's common practice to split up the props with required props on the top and optional props on the bottom, both in respective alphabetical order. We do this in our other components. This is also how Storybook Docs orders them. Should we keep them consistent?

2023-05-19 17:43 UTC, noranda approved these changes

2023-05-19 18:04 UTC, pgrippi approved these changes

2023-05-19 18:11 UTC, merged