[ECOMM-829] feat: Add fullWidth prop to EzFormControl
ezcater/recipe pull request #980
Opened 2023-06-16 20:38 UTC by royce-ezcater

## What did we change?
- Added optional `fullWidth` option to `EzFormControl`

## Why are we doing this?
- Jira story: https://ezcater.atlassian.net/browse/ECOMM-829
- Aims to remove the need for a Recipe override in store-next

## Screenshot(s) / Gif(s):

<details><summary>With fullWidth</summary>

https://github.com/ezcater/recipe/assets/104390061/2e9dd87f-a20d-4d86-9344-fe9b9a26a338

</details> 

<details><summary>Without fullWidth</summary>

https://github.com/ezcater/recipe/assets/104390061/c0c1115d-5430-4768-91db-7bf22f70a6dc

</details> 

## Checklist
- [x] Provide test coverage for the changes made
- [ ] Create a changeset (`yarn changeset`) with a summary of the changes
 
[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

2023-06-20 13:41 UTC, noranda requested changes
Thanks for your contribution to Recipe! This just needs some minor changes and it's good to go!

2023-06-20 13:41 UTC, noranda commented on .changeset/lovely-flies-rhyme.md
> +Added optional `fullWidth` option to `EzFormControl`
Suggest a slight change to this changeset based on our [versioning scheme](https://ezcater.github.io/recipe/guides/versioning-and-changelog#versioning-scheme).
```suggestion
feat: add optional fullWidth option to EzFormControl
```

2023-06-20 13:41 UTC, noranda commented on packages/recipe/src/components/EzFormControl/Implementations/EzFormControlMui.tsx
All the changes in this file can actually be removed. Since we pass all props through to MUI's `FormControl` [component](https://mui.com/material-ui/api/form-control/#props), which accepts `fullWidth`, this should work by default!

2023-06-20 15:43 UTC, royce-ezcater commented on packages/recipe/src/components/EzFormControl/Implementations/EzFormControlMui.tsx
Oh, great! Will make that change.

2023-06-20 16:08 UTC, royce-ezcater commented on .changeset/lovely-flies-rhyme.md
> +Added optional `fullWidth` option to `EzFormControl`
Addressed here: 2ff4976

2023-06-20 16:09 UTC, royce-ezcater commented on packages/recipe/src/components/EzFormControl/Implementations/EzFormControlMui.tsx
Addressed here: 6ad13a1

2023-06-22 13:12 UTC, pgrippi approved these changes

2023-06-22 13:37 UTC, merged